### ISSUE TITLE
Fixed size for Logical volume not working but %sizeVG works

### ISSUE THREAD

**Issue by R1200-GS** [zaxos/lvm-ansible-role#1]
when I specify lv_size: 8192 for instance I get the error that it is an invalid size, but a %sizeVG works
easy fix but quite difficult to spot :-)

- name: Create Logical Volume
  lvol:
    vg: "{{ item.vg_name }}"
    lv: "{{ item.lv_name }}" 
    size: " {{ item.lv_size | default('8G') }}"    <<<<<< there is a space in front of the {{ causing the error
    state: present
  with_items: "{{ lvm_volumes }}"
  when: >
    item.state is not defined or item.state == "present"

hope this is of use
Malcolm

**Comment by zaxos** [comment]
Nice catch, thank you! I only use default lv_size value in my daily routine so I had never come across this error.
